### ISSUE TITLE
Is Typhoeus thread safe with basic usage?

### ISSUE THREAD

**Issue by treeder** [typhoeus/typhoeus#301] opened 2013-06-03 21:13 UTC
See: https://github.com/iron-io/iron_core_ruby/issues/5

**Comment by nathanhoel** [comment] 2015-07-06 21:14
We were quite worried about this behaviour and so have been investigating it. 
I have been unable to reproduce these results (I used iron.io and everything to attempt to reproduce your results @carlallen)

Sometimes the 3rd or 4th thread would return the result and the first few threads would all have blank results (as desired). This convinced me because that seems like it would have caused all threads started before it to exhibit the race condition problem and return the response that the 3rd thread just got back.

I had a few questions: 
1. Did this problem occur regardless of headers sent?
This may seem like a harmless problem in some situations but when it comes to headers there are a few examples where it's terrible.
The first that came to mind is different 'Content-Type' heads like application/json vs. application/xml the bodies would be completely different.
Even worse 'Authorization' headers would mean different users accessing the same resource may get different results.

2. Were these problems maybe occuring using jRuby? I saw at least one other issue that was specific to jRuby when reading the issues.

Thanks,

**Comment by carlallen** [comment] 2015-07-06 21:18
I never tried jruby but I saw the same behavior in both mri and rubinius.

**Comment by carlallen** [comment] 2015-07-06 21:27
You could test this by creating a simple webserver that returns an incremented number on each GET request, then use a thread pool to request to the server multiple times.

Something like this:

```ruby
require 'thread/pool'

pool = Thread.pool(5)

url = "http://example.com/incrementer"

5.times{pool.process{puts Typhoeus::Request.get(url).body}}
```

I end up with outputs like:

```
1
1
1
1
1
```

When I would expect

```
1
2
3
4
5
```

**Comment by nathanhoel** [comment] 2015-07-06 23:00
Did you just test that again? Because this test seems like it would act exactly the same as the previous. I got the iron.io test to work, but it doesn't reproduce the issue. 
I always get the desired output back
```
{"messages":[{"id":"MESSAGE_ID","body":"Hello World","timeout":60,"push_status":{}}]}
{"messages":[]}
{"messages":[]}
{"messages":[]}
{"messages":[]}
```

**Comment by carlallen** [comment] 2015-07-06 23:22
Just tested it and it seems like it's doing what it should be. I hadn't tested this in over a year, so I can only assume the bug has since been fixed.

**Comment by carlallen** [comment] 2015-07-06 23:25
Hmm... looks like I haven't upgraded typhoeus since the last time, but I did change ruby versions. Let me look to see if it still fails in the old version.

**Comment by carlallen** [comment] 2015-07-06 23:40
Ok, looks like I was wrong. My project got upgraded to 0.6.5, and this issue seems to be fixed in that version. When I discovered this bug I was running 0.4.2. Based on what I see now, I would consider this bug fixed.

**Comment by i0rek** [comment] 2015-07-07 04:52
Thanks for your work @carlallen and @nathanhoel! I will close this issue then. If you run into any other problems, feel free to create a new one!

**Closed by i0rek** 2015-07-07 04:52 UTC
